import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import { ModeToggle } from "@/components/toggle";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Another Hélio Software",
  description: "Generated by Hélio Sal with <3",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <nav className="flex space-x-[25px]">
            <h1>How to get to the sun</h1>
            <ModeToggle/>
          </nav>
          {children}
        </ThemeProvider>
        
      </body>
    </html>
  );
}
